package factors;
/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

public class P12 {
	public static void solve_P12(){
		boolean found =false;
		long triNum = 0;
		int i = 1;
		int numDivisors = 0;
		
		while(!found){
			triNum += i;
			if (triNum % 2 == 0){
				numDivisors = countDivisors(triNum);
				System.out.println(i + " " + triNum + " " + numDivisors);
				
				if(numDivisors > 500){
					found = true;
					break;
				}
			}
			i++;
		}
		System.out.println(i + " " + triNum + " " + numDivisors);
	}
	public static int countDivisors(long n){
		int count = 0;
		for (long i = 1; i*i<=n; i++){
			if (n%i ==0){
				count += 2;
			}
		}
		if (Math.sqrt(n)*Math.sqrt(n) == n){
			count--;
		}
		return count;
	}
}
